directives:
- add_model:
    name: iiwa
    file: package://drake_models/iiwa_description/sdf/iiwa7_no_collision.sdf
    default_joint_positions:
        iiwa_joint_1: [0]
        iiwa_joint_2: [0.6]
        iiwa_joint_3: [0]
        iiwa_joint_4: [-1.75]
        iiwa_joint_5: [0]
        iiwa_joint_6: [ 1.0]
        iiwa_joint_7: [0]
        
- add_weld:
    parent: world
    child: iiwa::iiwa_link_0

- add_model:
    name: wsg
    file: package://manipulation/hydro/schunk_wsg_50_with_tip.sdf
- add_weld:
    parent: iiwa::iiwa_link_7
    child: wsg::body
    X_PC:
        translation: [0, 0, 0.114]
        rotation: !Rpy { deg: [90, 0, 90]}

- add_model:
    name: bin1
    file: package://manipulation/shelves.sdf
- add_weld:
    parent: world
    child: bin1::shelves_body
    X_PC:
        translation: [0.88, 0, 0.4]

- add_model:
    name: bin2
    file: package://manipulation/shelves.sdf
- add_weld:
    parent: world
    child: bin2::shelves_body
    X_PC:
        translation: [-0.88, 0, 0.4]
        rotation: !Rpy { deg: [0, 0, 180]}

- add_model:
    name: brick
    file: package://drake_models/manipulation_station/061_foam_brick.sdf
    default_free_body_pose:
        base_link:
            translation: [0.8, 0, 0.6]

model_drivers:
    iiwa: !IiwaDriver
      control_mode: position_only
      hand_model_name: wsg
    wsg: !SchunkWsgDriver {}